index_config:
  name: "nascimentos_example"
  number_of_shards: 1
  number_of_replicas: 0
  refresh_interval: "1s"

columns:
  - name: codigo_nascimento
    type: keyword
  - name: nome_completo
    type: text
    index_as: both
  - name: nome_mae
    type: text
    index_as: both
  - name: data_nascimento
    type: text
  - name: municipio_nascimento
    type: keyword
  - name: uf_nascimento
    type: keyword