index_name: enderecos_ficticios
source_table: enderecos_ficticios
es_connection_url: "http://localhost:9200/"
columns:
  - name: cep
    type: integer
    index: true
  - name: uf
    type: integer
    index: true
  - name: municipio
    type: string
    index_as: text
    index: true
  - name: bairro
    type: string
    index: true
  - name: logradouro
    type: string
    index_as: keyword
    index: true

index_settings:
  number_of_replicas: 1
  number_of_shards: 1
  refresh_interval: 0
